
name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: |
           echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" 
           echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build and push Docker image
      run: |
        docker build -t tziviarot/ci-cd:4.0 .
        docker push  tziviarot/ci-cd:4.0
