name: Build on Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2
      with:
        dockerfile: Dockerfile 

    - name: Build Docker Image
      run: docker build -t tziviarot/ci-cd:4.0 .

    - name: Run Docker Container
      run: docker run -e tziviarot/ci-cd:4.0
